@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package superscary.cyclopedia.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;