@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
package superscary.cyclopedia.manager;

import net.minecraft.FieldsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;